export const mockDeck = [
  'Altar of the Brood',
  'Archive Trap',
  'Ashiok, Dream Render',
  'Balustrade Spy',
  "Bane's Contingency",
  'Black Dragon Gate',
  'Bruvac the Grandiloquent',
  'Cabal Coffers',
  'Cast Down',
  'Castle Vantress',
  'Command Tower',
  'Consuming Aberration',
  'Court of Cunning',
  'Cut Your Losses',
  'Damnation',
  // 'Darksteel Plate',
  // 'Dauthi Voidwalker',
  // 'Deflection',
  // 'Demonic Tutor',
  // 'Devious Cover-Up',
  // "Didn't Say Please",
  // 'Dimir Guildgate',
  // 'Dismal Backwater',
  // 'Elder Brain',
  // 'Ertai Resurrected',
  // 'Exquisite Blood',
  // 'Extract from Darkness',
  // 'Feed the Serpent',
  // 'Fractured Sanity',
  // 'Fraying Sanity',
  // 'Glimpse the Unthinkable',
  // 'Gond Gate',
  // 'Grisly Spectacle',
  // 'Hall of Oracles',
  // 'Hall of Storm Giants',
  // 'Helm of Obedience',
  // 'Hive of the Eye Tyrant',
  // 'Ice Tunnel',
  // 'Imprisoned in the Moon',
  // 'Island',
  // 'Jace, Memory Adept',
  // 'Jidoor, Aristocratic Capital',
  // 'Keening Stone',
  // 'Leyline of the Void',
  // 'Lier, Disciple of the Drowned',
  // 'Lightning Greaves',
  // 'Maddening Cacophony',
  // 'Memory Erosion',
  // 'Mind Flayer',
  // 'Mindcrank',
  // 'Mirko Vosk, Mind Drinker',
  // 'Mistvault Bridge',
  // 'Morphic Pool',
  // 'Mothman Egg',
  // 'Notion Thief',
  // 'Pilfered Plans',
  // 'Professor Onyx',
  // 'Psychic Corrosion',
  // 'Psychic Strike',
  // 'Raise Dead',
  // 'Rhystic Study',
  // 'River of Tears',
  // 'Riverchurn Monument',
  // 'Ruin Crab',
  // 'Salt Marsh',
  // 'Sea Gate',
  // 'Sheoldred, Whispering One',
  // 'Shipwreck Marsh',
  // 'Singularity Rupture',
  // 'Sludge Monster',
  // 'Sol Ring',
  // 'Strip Mine',
  // 'Swamp',
  // "Tasha's Hideous Laughter",
  // 'Temple of Deceit',
  // 'Terisian Mindbreaker',
  // 'The Mindskinner',
  // 'The Mirari Conjecture',
  // 'The Water Crystal',
  // 'Thought Collapse',
  // 'Thought Scour',
  // 'Traumatize',
  // 'Umbris, Fear Manifest',
  // 'Undercity Informer',
  // 'Underground River',
  // 'Underground Sea',
  // 'Urborg, Tomb of Yawgmoth',
  // 'Vedalken Entrancer',
  // 'Watery Grave',
  // 'Witness Protection',
  // 'Wizard Class',
  // 'Phenax, God of Deception',
];
